version: '3.7'

services:
  mongo:
    image: mongo:latest
    restart: always
    container_name: 'mongo'
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    volumes:
      - ./db:/data/db
    ports:
      - 27017:27017