version: '3.6'

name: alpagotchi
services:
  database:
    container_name: database
    image: postgres
    restart: on-failure
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"

  bot:
    container_name: bot
    build:
      context: .
      dockerfile: Dockerfile
      args:
        TOKEN: ${TOKEN}
    restart: on-failure
    depends_on:
      - database

  adminer:
    container_name: adminer
    image: adminer
    restart: on-failure
    ports:
      - "8080:8080"
    depends_on:
      - database