version: '3.8'

name: alpagotchi
services:
  database:
    image: postgres:${POSTGRES_VERSION}
    restart: on-failure
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pg-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  bot:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        OWNER_ID: ${OWNER_ID}
        TOKEN: ${TOKEN}
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        POSTGRES_URL: ${POSTGRES_URL}
    depends_on:
      - database
    restart: on-failure

  adminer:
    image: adminer:${ADMINER_VERSION}
    depends_on:
      - database
    restart: on-failure
    environment:
      ADMINER_DESIGN: pepa-linha-dark
    ports:
      - "8080:8080"

volumes:
  pg-data: