version: '3.1'

services:
  database:
    image: postgres
    restart: on-failure
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"

  adminer:
    image: adminer
    restart: on-failure
    ports:
      - "8080:8080"